# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# ===== 隐藏导入 =====
hiddenimports = [
    'openpyxl',
    'openpyxl.cell',
    'openpyxl.reader',
    'openpyxl.workbook',
    'openpyxl.writer',
    'openpyxl.styles',
    'openpyxl.styles.numbers',
    'openpyxl.utils',
    'openpyxl.utils.cell',
    'openpyxl.formula',
    'openpyxl.comments',
    'openpyxl.drawing',
    'openpyxl.chart',
    'openpyxl.worksheet',
    'openpyxl.worksheet.cell_range',
    'openpyxl.packaging',
    'openpyxl.xml',
    'openpyxl.xml.functions',
    'pandas',
    'pandas.io',
    'pandas.io.excel',
    'pandas.core',
    'pandas.core.frame',
    'pandas.core.series',
    'pandas.core.indexes',
    'pandas.core.dtypes',
    'pandas.core.algorithms',
    'pandas.core.arrays',
    'pandas.core.groupby',
    'pandas.core.reshape',
    'pandas.core.sorting',
    'pandas.core.window',
    'pandas.io.common',
    'pandas.io.parsers',
    'pandas.io.parsers.readers',
    'numpy',
    'numpy.core',
    'numpy.core._methods',
    'numpy.lib',
    'numpy.lib.format',
    'numpy.random',
    'numpy.random._common',
    'numpy.linalg',
    'numpy.linalg.linalg',
    'numpy.fft',
    'numpy.polynomial',
    'numpy.ma',
    'numpy.matrixlib',
    'numpy.rec',
    'numpy.testing',
    'yaml',
    'yaml.loader',
    'yaml.dumper',
    'lxml',
    'lxml.etree',
    'lxml._elementpath',
    'PyQt5',
    'PyQt5.QtCore',
    'PyQt5.QtWidgets',
    'PyQt5.QtGui',
    'decimal',
    'datetime',
    'pathlib',
    'logging',
    'traceback',
    're',
    'copy',
    'shutil',
    'tempfile',
    'argparse',
    'enum',
    'dataclasses',
    'models',
    'models.transaction',
    'models.report_data',
    'services',
    'services.data_loader',
    'services.aggregator',
    'services.validator',
    'services.reporter',
    'services.direct_sheet_filler',
    'services.create_blank_template',
    'services.summary_service',
    'strategies',
    'strategies.classification_strategy',
    'strategies.default_strategy',
    'factories',
    'factories.reporter_factory',
]

# ===== 资源文件 =====
datas = [
    ('templates', 'templates'),  # 模板文件夹
    ('config.yaml', '.'),        # 配置文件
]

# ===== 如果有图标文件，添加到这里 =====
# 图标文件放在项目根目录，名称为 icon.ico
# 也可以使用绝对路径

a = Analysis(
    ['src/gui_main.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'PIL',
        'tkinter',
        'test',
        'tests',
        'unittest',
        'distutils',
        'setuptools',
        'ipython',
        'jupyter',
        'notebook',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyd = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# ===== 可执行文件配置 =====
exe = EXE(
    pyd,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='现金流量报表生成器',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # True=显示控制台窗口，False=不显示
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',  # ===== 添加图标 =====
)