# build.spec
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

hiddenimports = [
    'openpyxl',
    'openpyxl.cell',
    'openpyxl.reader',
    'openpyxl.workbook',
    'openpyxl.writer',
    'openpyxl.styles',
    'openpyxl.utils',
    'pandas',
    'pandas.io',
    'pandas.core',
    'numpy',
    'numpy.core',
    'numpy.lib',
    'numpy.random',
    'numpy.linalg',
    'numpy.fft',
    'numpy.polynomial',
    'numpy.ma',
    'numpy.matrixlib',
    'numpy.rec',
    'numpy.testing',
    'yaml',
    'lxml',
    'lxml.etree',
    'PyQt5',
    'PyQt5.QtCore',
    'PyQt5.QtWidgets',
    'PyQt5.QtGui',
    'decimal',
    'datetime',
    'pathlib',
    'logging',
    'traceback',
    'models',
    'models.transaction',
    'models.report_data',
    'services',
    'services.data_loader',
    'services.aggregator',
    'services.validator',
    'services.reporter',
    'services.direct_sheet_filler',
    'services.create_blank_template',
    'services.quarter_mapper',
    'strategies',
    'strategies.classification_strategy',
    'strategies.default_strategy',
    'factories',
    'factories.reporter_factory',
]

a = Analysis(
    ['src/gui_main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('config.yaml', '.'),
    ],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'PIL',
        'tkinter',
        'test',
        'tests',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyd = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyd,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='现金流量报表生成器',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)